name: Continuous Integration

on:
  schedule:
    # Run every hour
    - cron: */15 * * * *
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Start date'
        required: false
        default: '2022-02-20T04:51:27.000Z'
      end_date:
        description: 'End date'
        required: false
        default: '2023-05-26T04:51:27.000Z'

jobs:
  deploy:
    name: Builds and Deploys to github pages
    runs-on: ubuntu-latest
    environment: "Production"
    env:
      DATABASE_ID: ${{ secrets.DATABASE_ID }}
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: yarn --frozen-lockfile
      - name: Set Completed Date
        run: yarn run start
  update-old:
    name: Setups Completed date for all records
    if: github.event_name == 'workflow_dispatch'  # Only run when triggered manually
    runs-on: ubuntu-latest
    environment: "Production"
    env:
      DATABASE_ID: ${{ secrets.DATABASE_ID }}
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      START_DATE: ${{ inputs.start_date }}
      END_DATE: ${{ inputs.end_date }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: yarn --frozen-lockfile
      - name: Set Completed Date for all records
        run: yarn run complete-old
